title: Tikandevs Docs
description: A documentantion site for homelab and dev stuff
theme: just-the-docs
color_scheme: dark

url: https://just-the-docs.github.io

aux_links:
   Github Repository: https://github.com/tikandev/jekyll-documentation-site
